source 'https://rubygems.org'

ruby '>= 3.2'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'activerecord', '~> 8.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sqlite3', '~> 2.0'
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.9'
gem 'rake'
gem 'rack-cors', '~> 2.0'
gem 'rackup'
gem 'puma'
gem 'graphql', '~> 2.0'

group :development, :test do
end
